"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_@i^6u)e!w32#&i0062w5f(#5rddtis+$m10ehr=bcu@i7zp%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',
    'csp',  # For Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # For Content Security Policy
    
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/accounts/profile"
LOGOUT_REDIRECT_URL = "/accounts/profile"
# --- TASK 1: CUSTOM USER MODEL CONFIGURATION ---
# This tells Django to use our CustomUser model instead of the default User.
# Format: 'app_name.ModelName'
AUTH_USER_MODEL = 'bookshelf.CustomUser'


# ==============================================================================
# --- TASKS 3 & 4: SECURITY & HTTPS CONFIGURATION ---
# ==============================================================================
# These settings are for PRODUCTION. Running with these locally
# without an HTTPS setup (like Nginx) will cause issues.

# --- Task 4: HTTPS Redirects and HSTS ---
# WARNING: Setting this to True will redirect all HTTP to HTTPS.
# Only enable this in production after you have configured SSL/TLS.
#SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Instructs browsers to only access the site via HTTPS for the specified time.
#SECURE_HSTS_SECONDS = 31536000  # 1 year
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True

# --- Task 3 & 4: Secure Cookies ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Redirect all non-HTTPS requests to HTTPS.
SECURE_SSL_REDIRECT = True
# Enable HTTP Strict Transport Security (HSTS)
# Instructs browsers to only access the site via HTTPS.
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
# Ensures cookies are only sent over HTTPS.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# --- Task 3 & 4: Browser-Side Protections ---
# Prevents the site from being framed (protects against clickjacking)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Prevents browser from MIME-sniffing content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables browser's built-in XSS filter
SECURE_BROWSER_XSS_FILTER = True

# --- Task 3: Content Security Policy (CSP) ---
# Requires django-csp. This is a basic policy.
# 'self' allows content from your own domain.
# 'unsafe-inline' is often needed for inline styles/scripts but is less secure.
# Adjust this policy based on your specific needs.
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:") # 'data:' for inline images if any
CSP_FONT_SRC = ("'self'",)