# Generated by Django 5.2.8 on 2025-11-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': [('can_add_book', 'Can add a new book entry'), ('can_change_book', 'Can edit existing book entries'), ('can_delete_book', 'Can delete book entries')]},
        ),
    ]
